version : "2"
services :
  nginx:
    image: nginx:1.13.12-alpine
    container_name: nginx
    restart : always
    ports:
      - "80:80"
    volumes: 
      - "/home/statadmin/webstat/nginx-conf/default.conf:/etc/nginx/conf.d/default.conf"
  webstat:
    image: webstat:demo
    container_name : webstat
    restart: always
    ports: 
      - 3000:3001