version : "2"
services :
  webstat:
    image: webstat:demo
    container_name : webstat
    restart: always
    expose:
      - 3001
  nginx:
    image: nginx:1.13.12-alpine
    container_name: nginx
    restart : always
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - "/home/statadmin/webstat/nginx-conf/default.conf:/etc/nginx/conf.d/default.conf"
      - "/home/statadmin/data/certbot/conf:/etc/letsencrypt"
      - "/home/statadmin/data/certbot/www:/var/www/certbot"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
    - "/home/statadmin/data/certbot/conf:/etc/letsencrypt"
    - "/home/statadmin/data/certbot/www:/var/www/certbot"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"