version : "2"
services :
  webstat:
    image: webstat:demo
    container_name : webstat
    restart: always
    ports: 
      - "3001:3001"
    environment:
      - MONGODB_PORT=27018
      - MONGO_URL=spire.cpe.ku.ac.th 