version : "2"
services :
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: webstat
    ports: 
      - 27018:27017
    volumes:
      - /home/statadmin/data/database/prod:/data/db
  mongo-dev:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: webstat
    ports: 
      - 27017:27017
    volumes:
      - /home/statadmin/data/database/dev:/data/db