version : "3"
services :
  database:
    restart: always
    image: postgres:11
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: dondon
      POSTGRES_PASSWORD: dondon
      POSTGRES_DB : dondon
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080